"""add allowed_services column to users

Revision ID: 17af8b00c8d4
Revises: 31ba48a3aff9
Create Date: 2026-03-17 13:06:12.184936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17af8b00c8d4'
down_revision: Union[str, Sequence[str], None] = '31ba48a3aff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('allowed_services', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'allowed_services')
    # ### end Alembic commands ###
